package com.petushkov.webappcollections.models;


import io.swagger.annotations.ApiModelProperty;
import lombok.*;
import org.hibernate.Hibernate;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

@Getter
@Setter
@ToString
@Entity
@NoArgsConstructor
@Table(name = "roles")
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(notes = "id of role, generated by DB", example = "1")
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    @ApiModelProperty(notes = "name of collection", example = "ROLE_USER")
    private ERole name;


    public Role(ERole role) {
        this.name = role;
    }

}
